spring:
  application:
    name: at0m-eureka-server
server:
  port: 8761

---
spring:
  profiles: dev
eureka:
  environment: DEV
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---
spring:
  profiles: prod
eureka:
  environment: PROD
  instance:
    hostname: ec2-15-206-160-60.ap-south-1.compute.amazonaws.com
    preferIpAddress: true
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
---