spring:
  data:
    mongodb:
      port: 27017
      uri: mongodb://at0m:at0m@ec2-3-110-127-128.ap-south-1.compute.amazonaws.com:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
      auto-index-creation: true
      database: at0m

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://ec2-43-205-113-36.ap-south-1.compute.amazonaws.com:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  enabled: true

ribbon:
  listOfServers: http://ec2-43-205-113-36.ap-south-1.compute.amazonaws.com:8761/
  eureka:
    enabled: true

feign:
  client:
    config:
      default:
        logger-level: full
        read-timeout: 5000
        connect-timeout: 5000

logging:
  level:
    root: info