---
spring:
  profiles: dev
  data:
    mongodb:
      port: 27017
      host: localhost
      auto-index-creation: true
      database: at0m

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  enabled: true

ribbon:
  listOfServers: http://localhost:8761/
  eureka:
    enabled: true

---

spring:
  profiles: prod
  data:
    mongodb:
      port: 27017
      uri: mongodb://at0m:at0m@localhost:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256
      auto-index-creation: true
      database: at0m

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  enabled: true

ribbon:
  listOfServers: http://localhost:8761/
  eureka:
    enabled: true

---

feign:
  client:
    config:
      default:
        logger-level: full
        read-timeout: 5000
        connect-timeout: 5000

logging:
  level:
    root: info