spring:
  data:
    mongodb:
      username: at0m
      uri: mongodb://at0m@ec2-3-110-127-128.ap-south-1.compute.amazonaws.com:27017/?serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256&3t.uriVersion=3&3t.connection.name=at0m

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  enabled: true

ribbon:
  listOfServers: http://localhost:8761/
  eureka:
    enabled: true

feign:
  client:
    config:
      default:
        logger-level: full
        read-timeout: 5000
        connect-timeout: 5000

logging:
  level:
    root: info