spring:
  cloud:
    gateway:
      routes:
        - id: AT0M-PRODUCT-API
          uri: lb://AT0M-PRODUCT-API
          predicates:
            - Path=/api/produ**/**
          filters:
            - name: CircuitBreaker
              args:
                name: AT0M-PRODUCT-API
                fallbackuri: /api/produ**/**
        - id: AT0M-AVAILABLE-QUANTITY-API
          uri: lb://AT0M-AVAILABLE-QUANTITY-API
          predicates:
            - Path=/api/quant**/**
          filters:
            - name: CircuitBreaker
              args:
                name: AT0M-AVAILABLE-QUANTITY-API
                fallbackuri: /api/quant**/**

server:
  port: 8081