spring:
  application:
    name: at0m-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/girishu-ms26/Java-Microservice-Project
          searchPaths: at0m-config
          default-label: master

server:
  port: 8080

---
spring:
  profiles: dev

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  enabled: true
---
spring:
  profiles: prod

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://ec2-15-206-160-60.ap-south-1.compute.amazonaws.com:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
  enabled: true

---